// Generated by scripts/generate-openapi-tools.mjs from openapi/account.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const accountOperations = [
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "POST /account/v1/signup",
    "name": "account_signup",
    "title": "Create a new account",
    "description": "Create a new account\n\nCreates a new user account and returns the API key immediately. No authentication required.\n\nSecurity: this tool is disabled unless ENABLE_SENSITIVE_ACCOUNT_TOOLS is exactly true. Its result may contain credentials or a sensitive billing-session URL.",
    "method": "POST",
    "path": "/account/v1/signup",
    "inputSchema": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false,
      "required": [
        "email",
        "password"
      ]
    },
    "parameters": [
      {
        "publicName": "email",
        "wireName": "email",
        "location": "body",
        "required": true,
        "style": "json",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "email"
        }
      },
      {
        "publicName": "password",
        "wireName": "password",
        "location": "body",
        "required": true,
        "style": "json",
        "explode": true,
        "schema": {
          "type": "string",
          "minLength": 1
        }
      }
    ],
    "security": "public",
    "sensitive": true,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Create a new account",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "GET /account/v1/me",
    "name": "account_get_me",
    "title": "Get current user profile",
    "description": "Get current user profile\n\nReturns the authenticated user's profile including email, API key, tier, and subscriptions.\n\nSecurity: the MCP response omits the api_key field.",
    "method": "GET",
    "path": "/account/v1/me",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [
      "api_key"
    ],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get current user profile",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "POST /account/v1/api-key/rotate",
    "name": "account_rotate_api_key",
    "title": "Rotate API key",
    "description": "Rotate API key\n\nGenerates a new API key and invalidates the old one immediately.\nThe response includes the new key. All subsequent requests must use the new key.\n\nSecurity: this tool is disabled unless ENABLE_SENSITIVE_ACCOUNT_TOOLS is exactly true. Its result may contain credentials or a sensitive billing-session URL.",
    "method": "POST",
    "path": "/account/v1/api-key/rotate",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": true,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Rotate API key",
      "readOnlyHint": false,
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "GET /account/v1/subscriptions",
    "name": "account_get_subscriptions",
    "title": "List subscriptions",
    "description": "List subscriptions\n\nReturns all subscriptions for the authenticated user, enriched with billing provider status when available.",
    "method": "GET",
    "path": "/account/v1/subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "List subscriptions",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "POST /account/v1/subscriptions",
    "name": "account_change_subscription",
    "title": "Create or change subscription",
    "description": "Create or change subscription\n\nSubscribe to a sport, upgrade, or downgrade your plan.\n\nIf no payment method is on file, returns `402` with a `payment_url` for\nhosted billing checkout (human must visit to enter card details).\n\nIf a payment method exists, the subscription change is processed immediately\nand the response indicates `processing`. Poll `GET /account/v1/subscriptions`\nto check when the change is reflected.\n\nSecurity: this tool is disabled unless ENABLE_SENSITIVE_ACCOUNT_TOOLS is exactly true. Its result may contain credentials or a sensitive billing-session URL.",
    "method": "POST",
    "path": "/account/v1/subscriptions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sport": {
          "type": "string",
          "description": "Sport identifier (e.g., nba, nfl, all_access_v3)"
        },
        "tier": {
          "type": "string",
          "enum": [
            "paid",
            "paid_plus"
          ],
          "description": "Target subscription tier"
        }
      },
      "additionalProperties": false,
      "required": [
        "sport",
        "tier"
      ]
    },
    "parameters": [
      {
        "publicName": "sport",
        "wireName": "sport",
        "location": "body",
        "required": true,
        "style": "json",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Sport identifier (e.g., nba, nfl, all_access_v3)"
        }
      },
      {
        "publicName": "tier",
        "wireName": "tier",
        "location": "body",
        "required": true,
        "style": "json",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "paid",
            "paid_plus"
          ],
          "description": "Target subscription tier"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": true,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Create or change subscription",
      "readOnlyHint": false,
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "DELETE /account/v1/subscriptions/{type}",
    "name": "account_cancel_subscription",
    "title": "Cancel subscription",
    "description": "Cancel subscription\n\nCancel a subscription for a specific sport. Active subscriptions are\nscheduled for cancellation at the end of the billing period (access\ncontinues until then). Incomplete/unpaid subscriptions are canceled immediately.\n\nSecurity: this tool is disabled unless ENABLE_SENSITIVE_ACCOUNT_TOOLS is exactly true. Its result may contain credentials or a sensitive billing-session URL.",
    "method": "DELETE",
    "path": "/account/v1/subscriptions/{type}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "description": "Sport identifier (e.g., nba, nfl)"
        }
      },
      "additionalProperties": false,
      "required": [
        "type"
      ]
    },
    "parameters": [
      {
        "publicName": "type",
        "wireName": "type",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "description": "Sport identifier (e.g., nba, nfl)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": true,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Cancel subscription",
      "readOnlyHint": false,
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "GET /account/v1/plans",
    "name": "account_get_plans",
    "title": "List all available plans",
    "description": "List all available plans\n\nReturns all available subscription plans with pricing, rate limits, and links to per-sport OpenAPI specs. Includes paid-only StoryStats plans such as stories_wnba and stories_nfl. BALLDONTLIE all-access includes every sport, Lab, Webhooks, and StoryStats. No authentication required.",
    "method": "GET",
    "path": "/account/v1/plans",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "public",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "List all available plans",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "GET /account/v1/plans/{sport}",
    "name": "account_get_plans_by_sport",
    "title": "Get plan for a specific sport",
    "description": "Get plan for a specific sport\n\nReturns plan details for a single sport. No authentication required.",
    "method": "GET",
    "path": "/account/v1/plans/{sport}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sport": {
          "type": "string",
          "description": "Sport or product identifier (e.g., nba, nfl, stories_wnba, stories_nfl, all_access_v3)"
        }
      },
      "additionalProperties": false,
      "required": [
        "sport"
      ]
    },
    "parameters": [
      {
        "publicName": "sport",
        "wireName": "sport",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "string",
          "description": "Sport or product identifier (e.g., nba, nfl, stories_wnba, stories_nfl, all_access_v3)"
        }
      }
    ],
    "security": "public",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get plan for a specific sport",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "POST /account/v1/billing/checkout",
    "name": "account_create_checkout",
    "title": "Generate checkout URL",
    "description": "Generate checkout URL\n\nCreates a hosted billing checkout session for a specific plan and returns\nthe URL. A human must visit this URL to enter payment details.\n\nUse this when you want to proactively generate a payment link (e.g., for\nan onboarding flow). Unlike POST /subscriptions, this endpoint always\ngenerates a checkout URL regardless of whether a payment method exists.\n\nSecurity: this tool is disabled unless ENABLE_SENSITIVE_ACCOUNT_TOOLS is exactly true. Its result may contain credentials or a sensitive billing-session URL.",
    "method": "POST",
    "path": "/account/v1/billing/checkout",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sport": {
          "type": "string"
        },
        "tier": {
          "type": "string",
          "enum": [
            "paid",
            "paid_plus"
          ]
        }
      },
      "additionalProperties": false,
      "required": [
        "sport",
        "tier"
      ]
    },
    "parameters": [
      {
        "publicName": "sport",
        "wireName": "sport",
        "location": "body",
        "required": true,
        "style": "json",
        "explode": true,
        "schema": {
          "type": "string"
        }
      },
      {
        "publicName": "tier",
        "wireName": "tier",
        "location": "body",
        "required": true,
        "style": "json",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "paid",
            "paid_plus"
          ]
        }
      }
    ],
    "security": "apiKey",
    "sensitive": true,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [
      "checkout_url"
    ],
    "annotations": {
      "title": "Generate checkout URL",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/account.yml",
    "operationKey": "GET /account/v1/billing/portal",
    "name": "account_get_billing_portal",
    "title": "Get billing portal URL",
    "description": "Get billing portal URL\n\nGenerates a hosted billing portal URL where a human can update payment\nmethods, view invoices, and manage billing details.\n\nSecurity: this tool is disabled unless ENABLE_SENSITIVE_ACCOUNT_TOOLS is exactly true. Its result may contain credentials or a sensitive billing-session URL.",
    "method": "GET",
    "path": "/account/v1/billing/portal",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": true,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [
      "portal_url"
    ],
    "annotations": {
      "title": "Get billing portal URL",
      "readOnlyHint": false,
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
