// Generated by scripts/generate-openapi-tools.mjs from openapi/f1.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const f1Operations = [
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/drivers",
    "name": "f1_get_drivers",
    "title": "Get F1 drivers",
    "description": "Get F1 drivers\n\nRetrieve a list of Formula 1 drivers with optional filtering. FREE tier.",
    "method": "GET",
    "path": "/f1/v1/drivers",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "search": {
          "type": "string",
          "description": "Search drivers by name"
        },
        "country_code": {
          "type": "string",
          "description": "Filter by ISO country code"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific driver IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search drivers by name"
        }
      },
      {
        "publicName": "country_code",
        "wireName": "country_code",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by ISO country code"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 drivers",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/teams",
    "name": "f1_get_teams",
    "title": "Get F1 teams",
    "description": "Get F1 teams\n\nRetrieve a list of Formula 1 teams with optional filtering. FREE tier.",
    "method": "GET",
    "path": "/f1/v1/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "search": {
          "type": "string",
          "description": "Search teams by name"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific team IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search teams by name"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 teams",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/circuits",
    "name": "f1_get_circuits",
    "title": "Get F1 circuits",
    "description": "Get F1 circuits\n\nRetrieve a list of Formula 1 circuits with optional filtering. FREE tier.",
    "method": "GET",
    "path": "/f1/v1/circuits",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "search": {
          "type": "string",
          "description": "Search circuits by name"
        },
        "country_code": {
          "type": "string",
          "description": "Filter by ISO country code"
        },
        "circuit_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific circuit IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search circuits by name"
        }
      },
      {
        "publicName": "country_code",
        "wireName": "country_code",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by ISO country code"
        }
      },
      {
        "publicName": "circuit_ids",
        "wireName": "circuit_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific circuit IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 circuits",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/seasons",
    "name": "f1_get_seasons",
    "title": "Get F1 seasons",
    "description": "Get F1 seasons\n\nRetrieve a list of Formula 1 seasons. FREE tier.",
    "method": "GET",
    "path": "/f1/v1/seasons",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 seasons",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/events",
    "name": "f1_get_events",
    "title": "Get F1 events",
    "description": "Get F1 events\n\nRetrieve a list of Formula 1 race events (Grand Prix weekends) with optional filtering. FREE tier.",
    "method": "GET",
    "path": "/f1/v1/events",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season year"
        },
        "status": {
          "type": "string",
          "description": "Filter by event status"
        },
        "circuit_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by circuit IDs"
        },
        "event_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific event IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season year"
        }
      },
      {
        "publicName": "status",
        "wireName": "status",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by event status"
        }
      },
      {
        "publicName": "circuit_ids",
        "wireName": "circuit_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by circuit IDs"
        }
      },
      {
        "publicName": "event_ids",
        "wireName": "event_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by specific event IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 events",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/sessions",
    "name": "f1_get_sessions",
    "title": "Get F1 sessions",
    "description": "Get F1 sessions\n\nRetrieve a list of Formula 1 sessions (Practice, Qualifying, Sprint, Race) with optional filtering. Requires PAID tier or higher.",
    "method": "GET",
    "path": "/f1/v1/sessions",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "event_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by event IDs"
        },
        "type": {
          "type": "string",
          "description": "Filter by session type (Practice, Qualifying, Sprint, Race)"
        },
        "status": {
          "type": "string",
          "description": "Filter by session status"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "event_ids",
        "wireName": "event_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by event IDs"
        }
      },
      {
        "publicName": "type",
        "wireName": "type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by session type (Practice, Qualifying, Sprint, Race)"
        }
      },
      {
        "publicName": "status",
        "wireName": "status",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by session status"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 sessions",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/session_results",
    "name": "f1_get_session_results",
    "title": "Get F1 session results",
    "description": "Get F1 session results\n\nRetrieve Formula 1 session results (finishing positions, laps completed, etc.) with optional filtering. Requires PAID tier or higher.",
    "method": "GET",
    "path": "/f1/v1/session_results",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 session results",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/driver_standings",
    "name": "f1_get_driver_standings",
    "title": "Get F1 driver standings",
    "description": "Get F1 driver standings\n\nRetrieve Formula 1 Driver Championship standings for a specific season. Requires PAID tier or higher.",
    "method": "GET",
    "path": "/f1/v1/driver_standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Season year (required)"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year (required)"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 driver standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/team_standings",
    "name": "f1_get_team_standings",
    "title": "Get F1 team standings",
    "description": "Get F1 team standings\n\nRetrieve Formula 1 Constructors Championship standings for a specific season. Requires PAID tier or higher.",
    "method": "GET",
    "path": "/f1/v1/team_standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Season year (required)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year (required)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 team standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/lap_times",
    "name": "f1_get_lap_times",
    "title": "Get F1 lap times",
    "description": "Get F1 lap times\n\nRetrieve detailed lap-by-lap timing data for Formula 1 sessions. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/lap_times",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs (required)"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        },
        "lap_number": {
          "type": "integer",
          "description": "Filter by specific lap number"
        }
      },
      "additionalProperties": false,
      "required": [
        "session_ids"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs (required)"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      {
        "publicName": "lap_number",
        "wireName": "lap_number",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by specific lap number"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 lap times",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/qualifying_results",
    "name": "f1_get_qualifying_results",
    "title": "Get F1 qualifying results",
    "description": "Get F1 qualifying results\n\nRetrieve detailed qualifying session results including Q1, Q2, and Q3 times. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/qualifying_results",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 qualifying results",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/pit_stops",
    "name": "f1_get_pit_stops",
    "title": "Get F1 pit stops",
    "description": "Get F1 pit stops\n\nRetrieve pit stop data including duration and timing. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/pit_stops",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 pit stops",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/tire_stints",
    "name": "f1_get_tire_stints",
    "title": "Get F1 tire stints",
    "description": "Get F1 tire stints\n\nRetrieve tire compound and stint data for each driver. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/tire_stints",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 tire stints",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/session_weather",
    "name": "f1_get_session_weather",
    "title": "Get F1 session weather",
    "description": "Get F1 session weather\n\nRetrieve weather conditions during Formula 1 sessions. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/session_weather",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 session weather",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/race_control_messages",
    "name": "f1_get_race_control_messages",
    "title": "Get F1 race control messages",
    "description": "Get F1 race control messages\n\nRetrieve race control messages including flags, safety car, and DRS notifications. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/race_control_messages",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "category": {
          "type": "string",
          "description": "Filter by message category"
        },
        "flag": {
          "type": "string",
          "description": "Filter by flag type"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "category",
        "wireName": "category",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by message category"
        }
      },
      {
        "publicName": "flag",
        "wireName": "flag",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by flag type"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 race control messages",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/position_history",
    "name": "f1_get_position_history",
    "title": "Get F1 position history",
    "description": "Get F1 position history\n\nRetrieve lap-by-lap position changes for drivers during sessions. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/position_history",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs (required)"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        },
        "lap_number": {
          "type": "integer",
          "description": "Filter by specific lap number"
        }
      },
      "additionalProperties": false,
      "required": [
        "session_ids"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs (required)"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      {
        "publicName": "lap_number",
        "wireName": "lap_number",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by specific lap number"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 position history",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/session_timing_stats",
    "name": "f1_get_session_timing_stats",
    "title": "Get F1 session timing stats",
    "description": "Get F1 session timing stats\n\nRetrieve detailed timing statistics including best laps, sector times, and speed trap data. Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/session_timing_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "driver_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "driver_ids",
        "wireName": "driver_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by driver IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 session timing stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/track_status",
    "name": "f1_get_track_status",
    "title": "Get F1 track status",
    "description": "Get F1 track status\n\nRetrieve track status changes during sessions (green flag, yellow flag, safety car, etc.). Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/track_status",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "session_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        },
        "status": {
          "type": "string",
          "description": "Filter by track status code"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "session_ids",
        "wireName": "session_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by session IDs"
        }
      },
      {
        "publicName": "status",
        "wireName": "status",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by track status code"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 track status",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/f1.yml",
    "operationKey": "GET /f1/v1/odds/futures",
    "name": "f1_get_futures_odds",
    "title": "Get F1 futures odds",
    "description": "Get F1 futures odds\n\nRetrieve futures betting odds for Formula 1 championships (e.g., driver championship winner,\nconstructor championship winner). Requires PAID+ tier.",
    "method": "GET",
    "path": "/f1/v1/odds/futures",
    "inputSchema": {
      "type": "object",
      "properties": {
        "event_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by event IDs"
        },
        "market_type": {
          "type": "string",
          "description": "Filter by market type (e.g., driver_championship, constructor_championship)"
        },
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "event_ids",
        "wireName": "event_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by event IDs"
        }
      },
      {
        "publicName": "market_type",
        "wireName": "market_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by market type (e.g., driver_championship, constructor_championship)"
        }
      },
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get F1 futures odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
