// Generated by scripts/generate-openapi-tools.mjs from openapi/mlb.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const mlbOperations = [
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/teams",
    "name": "mlb_get_teams",
    "title": "Get MLB teams",
    "description": "Get MLB teams",
    "method": "GET",
    "path": "/mlb/v1/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "division": {
          "type": "string",
          "description": "Filter by division"
        },
        "league": {
          "type": "string",
          "description": "Filter by league"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "division",
        "wireName": "division",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by division"
        }
      },
      {
        "publicName": "league",
        "wireName": "league",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by league"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB teams",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/teams/{id}",
    "name": "mlb_get_team_by_id",
    "title": "Get specific MLB team",
    "description": "Get specific MLB team",
    "method": "GET",
    "path": "/mlb/v1/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Team ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Team ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific MLB team",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/players",
    "name": "mlb_get_players",
    "title": "Get MLB players",
    "description": "Get MLB players",
    "method": "GET",
    "path": "/mlb/v1/players",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/players/{id}",
    "name": "mlb_get_player_by_id",
    "title": "Get specific MLB player",
    "description": "Get specific MLB player",
    "method": "GET",
    "path": "/mlb/v1/players/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Player ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Player ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific MLB player",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/player_injuries",
    "name": "mlb_get_player_injuries",
    "title": "Get MLB player injuries",
    "description": "Get MLB player injuries",
    "method": "GET",
    "path": "/mlb/v1/player_injuries",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB player injuries",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/players/active",
    "name": "mlb_get_active_players",
    "title": "Get active MLB players",
    "description": "Get active MLB players",
    "method": "GET",
    "path": "/mlb/v1/players/active",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get active MLB players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/games",
    "name": "mlb_get_games",
    "title": "Get MLB games",
    "description": "Get MLB games",
    "method": "GET",
    "path": "/mlb/v1/games",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason games"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "spring_training",
            "regular",
            "postseason"
          ],
          "description": "Filter by season type (spring_training, regular, or postseason). Takes precedence over postseason parameter."
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason games"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "spring_training",
            "regular",
            "postseason"
          ],
          "description": "Filter by season type (spring_training, regular, or postseason). Takes precedence over postseason parameter."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB games",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/games/{id}",
    "name": "mlb_get_game_by_id",
    "title": "Get specific MLB game",
    "description": "Get specific MLB game",
    "method": "GET",
    "path": "/mlb/v1/games/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Game ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Game ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific MLB game",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/stats",
    "name": "mlb_get_stats",
    "title": "Get MLB stats",
    "description": "Get MLB stats",
    "method": "GET",
    "path": "/mlb/v1/stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/standings",
    "name": "mlb_get_standings",
    "title": "Get MLB team standings",
    "description": "Get MLB team standings",
    "method": "GET",
    "path": "/mlb/v1/standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "season": {
          "type": "integer",
          "description": "The season year"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The season year"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB team standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/season_stats",
    "name": "mlb_get_season_stats",
    "title": "Get MLB season stats",
    "description": "Get MLB season stats",
    "method": "GET",
    "path": "/mlb/v1/season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "The season year"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_id": {
          "type": "integer",
          "description": "Filter by team ID"
        },
        "postseason": {
          "type": "boolean",
          "description": "Get postseason stats"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "spring_training",
            "regular",
            "postseason"
          ],
          "description": "Filter by season type. Takes precedence over postseason parameter."
        },
        "sort_by": {
          "type": "string",
          "description": "Attribute to sort by"
        },
        "sort_order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort order"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The season year"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_id",
        "wireName": "team_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by team ID"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Get postseason stats"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "spring_training",
            "regular",
            "postseason"
          ],
          "description": "Filter by season type. Takes precedence over postseason parameter."
        }
      },
      {
        "publicName": "sort_by",
        "wireName": "sort_by",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Attribute to sort by"
        }
      },
      {
        "publicName": "sort_order",
        "wireName": "sort_order",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort order"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB season stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/teams/season_stats",
    "name": "mlb_get_team_season_stats",
    "title": "Get MLB team season stats",
    "description": "Get MLB team season stats",
    "method": "GET",
    "path": "/mlb/v1/teams/season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "season": {
          "type": "integer",
          "description": "The season year"
        },
        "team_id": {
          "type": "integer",
          "description": "Filter by team ID"
        },
        "postseason": {
          "type": "boolean",
          "description": "Get postseason stats"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "spring_training",
            "regular",
            "postseason"
          ],
          "description": "Filter by season type. Takes precedence over postseason parameter."
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The season year"
        }
      },
      {
        "publicName": "team_id",
        "wireName": "team_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by team ID"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Get postseason stats"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "spring_training",
            "regular",
            "postseason"
          ],
          "description": "Filter by season type. Takes precedence over postseason parameter."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB team season stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/players/splits",
    "name": "mlb_get_player_splits",
    "title": "Get MLB player splits",
    "description": "Get MLB player splits\n\nGet player splits grouped by split_category (e.g., vs RHP/LHP, by month, by opponent, etc.)",
    "method": "GET",
    "path": "/mlb/v1/players/splits",
    "inputSchema": {
      "type": "object",
      "properties": {
        "player_id": {
          "type": "integer",
          "description": "Player ID"
        },
        "season": {
          "type": "integer",
          "description": "Season year"
        }
      },
      "additionalProperties": false,
      "required": [
        "player_id",
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Player ID"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB player splits",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/players/versus",
    "name": "mlb_get_player_versus",
    "title": "Get MLB player vs player matchups",
    "description": "Get MLB player vs player matchups\n\nGet head-to-head batting statistics for batter against pitchers for a specific team, or pitcher against batters from a specific team",
    "method": "GET",
    "path": "/mlb/v1/players/versus",
    "inputSchema": {
      "type": "object",
      "properties": {
        "player_id": {
          "type": "integer",
          "description": "Player ID (batter or pitcher)"
        },
        "opponent_team_id": {
          "type": "integer",
          "description": "Opponent team ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "player_id",
        "opponent_team_id"
      ]
    },
    "parameters": [
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Player ID (batter or pitcher)"
        }
      },
      {
        "publicName": "opponent_team_id",
        "wireName": "opponent_team_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Opponent team ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB player vs player matchups",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/plays",
    "name": "mlb_get_plays",
    "title": "Get MLB play-by-play data",
    "description": "Get MLB play-by-play data\n\nReturns play-by-play data for a specific game including game state, scoring plays, and batted ball details. Plays are ordered by `order` ascending by default. Set `sort_order=desc` to return the latest plays first. Keep the same `sort_order` when following pagination cursors.",
    "method": "GET",
    "path": "/mlb/v1/plays",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID (required)"
        },
        "sort_order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        },
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID (required)"
        }
      },
      {
        "publicName": "sort_order",
        "wireName": "sort_order",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      },
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB play-by-play data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/plate_appearances",
    "name": "mlb_get_plate_appearances",
    "title": "Get MLB plate appearance data",
    "description": "Get MLB plate appearance data\n\nReturns plate appearance data for a specific game. Each plate appearance includes the outcome and all individual pitches with detailed advanced pitch metrics. All plate appearances for the game are returned in a single response (no pagination).",
    "method": "GET",
    "path": "/mlb/v1/plate_appearances",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID (required)"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID (required)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB plate appearance data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/pitcher_pitch_type_game_stats",
    "name": "mlb_get_pitcher_pitch_type_game_stats",
    "title": "Get MLB pitcher pitch type game stats",
    "description": "Get MLB pitcher pitch type game stats\n\nReturns per-game pitcher pitch-type usage, command, whiff/contact, and damage metrics.",
    "method": "GET",
    "path": "/mlb/v1/pitcher_pitch_type_game_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season year"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        },
        "pitch_type": {
          "type": "string",
          "description": "Filter by pitch type code"
        },
        "sort_by": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba"
          ],
          "description": "Attribute to sort by"
        },
        "sort_order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season year"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        }
      },
      {
        "publicName": "pitch_type",
        "wireName": "pitch_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by pitch type code"
        }
      },
      {
        "publicName": "sort_by",
        "wireName": "sort_by",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba"
          ],
          "description": "Attribute to sort by"
        }
      },
      {
        "publicName": "sort_order",
        "wireName": "sort_order",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB pitcher pitch type game stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/hitter_pitch_type_game_stats",
    "name": "mlb_get_hitter_pitch_type_game_stats",
    "title": "Get MLB hitter pitch type game stats",
    "description": "Get MLB hitter pitch type game stats\n\nReturns per-game hitter pitch-type usage, command, whiff/contact, and damage metrics.",
    "method": "GET",
    "path": "/mlb/v1/hitter_pitch_type_game_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season year"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        },
        "pitch_type": {
          "type": "string",
          "description": "Filter by pitch type code"
        },
        "sort_by": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba"
          ],
          "description": "Attribute to sort by"
        },
        "sort_order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season year"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        }
      },
      {
        "publicName": "pitch_type",
        "wireName": "pitch_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by pitch type code"
        }
      },
      {
        "publicName": "sort_by",
        "wireName": "sort_by",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba"
          ],
          "description": "Attribute to sort by"
        }
      },
      {
        "publicName": "sort_order",
        "wireName": "sort_order",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB hitter pitch type game stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/pitcher_pitch_type_season_stats",
    "name": "mlb_get_pitcher_pitch_type_season_stats",
    "title": "Get MLB pitcher pitch type season stats",
    "description": "Get MLB pitcher pitch type season stats\n\nReturns season-level pitcher pitch-type usage, command, whiff/contact, and damage metrics.",
    "method": "GET",
    "path": "/mlb/v1/pitcher_pitch_type_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "The season year"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        },
        "pitch_type": {
          "type": "string",
          "description": "Filter by pitch type code"
        },
        "sort_by": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba",
            "last_game_date"
          ],
          "description": "Attribute to sort by"
        },
        "sort_order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The season year"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        }
      },
      {
        "publicName": "pitch_type",
        "wireName": "pitch_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by pitch type code"
        }
      },
      {
        "publicName": "sort_by",
        "wireName": "sort_by",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba",
            "last_game_date"
          ],
          "description": "Attribute to sort by"
        }
      },
      {
        "publicName": "sort_order",
        "wireName": "sort_order",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB pitcher pitch type season stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/hitter_pitch_type_season_stats",
    "name": "mlb_get_hitter_pitch_type_season_stats",
    "title": "Get MLB hitter pitch type season stats",
    "description": "Get MLB hitter pitch type season stats\n\nReturns season-level hitter pitch-type usage, command, whiff/contact, and damage metrics.",
    "method": "GET",
    "path": "/mlb/v1/hitter_pitch_type_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "The season year"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        },
        "pitch_type": {
          "type": "string",
          "description": "Filter by pitch type code"
        },
        "sort_by": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba",
            "last_game_date"
          ],
          "description": "Attribute to sort by"
        },
        "sort_order": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The season year"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "postseason"
          ],
          "description": "Filter by regular season or postseason"
        }
      },
      {
        "publicName": "pitch_type",
        "wireName": "pitch_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by pitch type code"
        }
      },
      {
        "publicName": "sort_by",
        "wireName": "sort_by",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "pitch_count",
            "pitch_usage_percent",
            "zone_percent",
            "chase_percent",
            "command_percent",
            "swing_count",
            "whiff_percent",
            "contact_percent",
            "called_strike_count",
            "called_ball_count",
            "pa_count",
            "at_bat_count",
            "hit_count",
            "home_run_count",
            "walk_count",
            "strikeout_count",
            "total_bases",
            "damage_count",
            "ba",
            "slg",
            "woba",
            "xwoba",
            "last_game_date"
          ],
          "description": "Attribute to sort by"
        }
      },
      {
        "publicName": "sort_order",
        "wireName": "sort_order",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "asc",
            "desc"
          ],
          "description": "Sort direction. Defaults to `asc`."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB hitter pitch type season stats",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/odds",
    "name": "mlb_get_odds",
    "title": "Get MLB betting odds",
    "description": "Get MLB betting odds\n\nRetrieve betting odds for MLB games. Either dates or game_ids is required.",
    "method": "GET",
    "path": "/mlb/v1/odds",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by specific dates (YYYY-MM-DD format)"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by specific dates (YYYY-MM-DD format)"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/odds/markets",
    "name": "mlb_get_odds_markets",
    "title": "Get all current MLB betting markets",
    "description": "Get all current MLB betting markets\n\nRetrieve the current market catalog for one MLB game. This open-ended endpoint includes game, team, inning, player, comparison, milestone, and other market structures without requiring market names or keys to come from a fixed list.\n\nComplete current catalogs are available for DraftKings and FanDuel. Sportsbooks supported by the simplified odds or player-props endpoints may not appear here until complete market catalogs are available.\n\nMarkets are paginated as complete units. Outcomes may have null prices while their status is `locked` or `suspended`. Use `/mlb/v1/odds/player_props` when you only need the simplified single-player over/under and milestone projection.",
    "method": "GET",
    "path": "/mlb/v1/odds/markets",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "Game ID to retrieve markets for"
        },
        "vendors": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors. Complete current catalogs are available for `draftkings` and `fanduel`."
        },
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Game ID to retrieve markets for"
        }
      },
      {
        "publicName": "vendors",
        "wireName": "vendors",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors. Complete current catalogs are available for `draftkings` and `fanduel`."
        }
      },
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get all current MLB betting markets",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/odds/opening",
    "name": "mlb_get_odds_opening",
    "title": "Get MLB opening betting odds",
    "description": "Get MLB opening betting odds\n\nRetrieve historical opening betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/mlb/v1/odds/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB opening betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/odds/player_props",
    "name": "mlb_get_player_props",
    "title": "Get MLB player prop betting odds",
    "description": "Get MLB player prop betting odds\n\nRetrieve live player prop betting data for MLB games. Player prop data is LIVE and updated in real-time.\nWe do not store historical data. As games near completion, many (or all) player props may be removed from sportsbooks.\n\n**Note:** This endpoint returns all player props for the specified game in a single response. Pagination is not supported.\n\nThe API supports two market types:\n- **over_under**: Traditional over/under markets where users can bet on whether a player will go over or under a specific line value\n- **milestone**: Milestone markets where users bet on whether a player will reach a specific achievement\n\nProp types are open-ended. Common examples include:\n- Batter props: hits, home_runs, total_bases, rbis, stolen_bases, singles, doubles, triples, walks, strikeouts, runs_scored, and hits_runs_rbis\n- Pitcher props: pitcher_strikeouts, pitcher_outs, pitcher_hits_allowed, pitcher_walks, pitcher_earned_runs, and pitcher_record_a_win\n\nNewly available compatible single-player markets can appear without a documentation enum update. Use `/mlb/v1/odds/markets` for the complete current market catalog, including structures that do not fit this simplified response.\n\nAvailable vendors: betmgm, betrivers, caesars, draftkings, fanatics, fanduel",
    "method": "GET",
    "path": "/mlb/v1/odds/player_props",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID to retrieve player props for (required)"
        },
        "player_id": {
          "type": "integer",
          "description": "Filter props for a specific player"
        },
        "prop_type": {
          "type": "string",
          "description": "Filter by an open-ended prop type string."
        },
        "vendors": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "betmgm",
              "betrivers",
              "caesars",
              "draftkings",
              "fanatics",
              "fanduel"
            ]
          },
          "description": "Filter by specific sportsbook vendors (e.g., draftkings, fanduel). If not provided, returns props from all available vendors."
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID to retrieve player props for (required)"
        }
      },
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter props for a specific player"
        }
      },
      {
        "publicName": "prop_type",
        "wireName": "prop_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by an open-ended prop type string."
        }
      },
      {
        "publicName": "vendors",
        "wireName": "vendors",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "betmgm",
              "betrivers",
              "caesars",
              "draftkings",
              "fanatics",
              "fanduel"
            ]
          },
          "description": "Filter by specific sportsbook vendors (e.g., draftkings, fanduel). If not provided, returns props from all available vendors."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB player prop betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/odds/player_props/opening",
    "name": "mlb_get_odds_player_props_opening",
    "title": "Get MLB opening player prop odds",
    "description": "Get MLB opening player prop odds\n\nRetrieve historical opening player prop betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/mlb/v1/odds/player_props/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID to retrieve opening player props for"
        },
        "player_id": {
          "type": "integer",
          "description": "Filter props for a specific player"
        },
        "prop_type": {
          "type": "string",
          "description": "Filter by prop type"
        },
        "vendors": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID to retrieve opening player props for"
        }
      },
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter props for a specific player"
        }
      },
      {
        "publicName": "prop_type",
        "wireName": "prop_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by prop type"
        }
      },
      {
        "publicName": "vendors",
        "wireName": "vendors",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB opening player prop odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/mlb.yml",
    "operationKey": "GET /mlb/v1/lineups",
    "name": "mlb_get_lineups",
    "title": "Get MLB game lineups",
    "description": "Get MLB game lineups\n\nGet pre-game batting lineups and probable pitchers for MLB games. Lineups typically appear 1-2 hours before first pitch. Lineup data is available starting from the 2026 season.",
    "method": "GET",
    "path": "/mlb/v1/lineups",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get MLB game lineups",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
