// Generated by scripts/generate-openapi-tools.mjs from openapi/ncaab.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const ncaabOperations = [
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/conferences",
    "name": "ncaab_get_conferences",
    "title": "Get NCAAB conferences",
    "description": "Get NCAAB conferences",
    "method": "GET",
    "path": "/ncaab/v1/conferences",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB conferences",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/conferences/{id}",
    "name": "ncaab_get_conference_by_id",
    "title": "Get specific NCAAB conference",
    "description": "Get specific NCAAB conference",
    "method": "GET",
    "path": "/ncaab/v1/conferences/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Conference ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Conference ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAB conference",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/teams",
    "name": "ncaab_get_teams",
    "title": "Get NCAAB teams",
    "description": "Get NCAAB teams",
    "method": "GET",
    "path": "/ncaab/v1/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conference_id": {
          "type": "integer",
          "description": "Filter by conference ID"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "conference_id",
        "wireName": "conference_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by conference ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB teams",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/teams/{id}",
    "name": "ncaab_get_team_by_id",
    "title": "Get specific NCAAB team",
    "description": "Get specific NCAAB team",
    "method": "GET",
    "path": "/ncaab/v1/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Team ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Team ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAB team",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/players",
    "name": "ncaab_get_players",
    "title": "Get NCAAB players",
    "description": "Get NCAAB players",
    "method": "GET",
    "path": "/ncaab/v1/players",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        },
        "position": {
          "type": "string",
          "description": "Filter by position"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      {
        "publicName": "position",
        "wireName": "position",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by position"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/players/{id}",
    "name": "ncaab_get_player_by_id",
    "title": "Get specific NCAAB player",
    "description": "Get specific NCAAB player",
    "method": "GET",
    "path": "/ncaab/v1/players/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Player ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Player ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAB player",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/players/active",
    "name": "ncaab_get_active_players",
    "title": "Get active NCAAB players",
    "description": "Get active NCAAB players",
    "method": "GET",
    "path": "/ncaab/v1/players/active",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        },
        "position": {
          "type": "string",
          "description": "Filter by position"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      {
        "publicName": "position",
        "wireName": "position",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by position"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get active NCAAB players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/standings",
    "name": "ncaab_get_standings",
    "title": "Get NCAAB team standings",
    "description": "Get NCAAB team standings\n\nGet team standings. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "season": {
          "type": "integer",
          "description": "Season year (e.g. 2025 for 2025-26 season)"
        },
        "conference_id": {
          "type": "integer",
          "description": "Filter by conference ID (REQUIRED if season is provided)"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "conference_id",
        "wireName": "conference_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by conference ID (REQUIRED if season is provided)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB team standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/games",
    "name": "ncaab_get_games",
    "title": "Get NCAAB games",
    "description": "Get NCAAB games\n\nGet games. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/games",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date (YYYY-MM-DD)"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date (YYYY-MM-DD)"
        },
        "weeks": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by week numbers"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "weeks",
        "wireName": "weeks[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by week numbers"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB games",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/games/{id}",
    "name": "ncaab_get_game_by_id",
    "title": "Get specific NCAAB game",
    "description": "Get specific NCAAB game",
    "method": "GET",
    "path": "/ncaab/v1/games/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Game ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Game ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAB game",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/rankings",
    "name": "ncaab_get_rankings",
    "title": "Get NCAAB rankings",
    "description": "Get NCAAB rankings\n\nGet team rankings. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/rankings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        },
        "week": {
          "type": "integer",
          "description": "Filter by week number"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "week",
        "wireName": "week",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by week number"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB rankings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/plays",
    "name": "ncaab_get_plays",
    "title": "Get NCAAB play-by-play data",
    "description": "Get NCAAB play-by-play data",
    "method": "GET",
    "path": "/ncaab/v1/plays",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "Game ID (REQUIRED)"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Game ID (REQUIRED)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB play-by-play data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/player_stats",
    "name": "ncaab_get_player_stats",
    "title": "Get NCAAB player game statistics",
    "description": "Get NCAAB player game statistics\n\nGet player statistics. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/player_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "weeks": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by week numbers"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "weeks",
        "wireName": "weeks[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by week numbers"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB player game statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/team_stats",
    "name": "ncaab_get_team_stats",
    "title": "Get NCAAB team game statistics",
    "description": "Get NCAAB team game statistics\n\nGet team statistics. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/team_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        },
        "weeks": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by week numbers"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      {
        "publicName": "weeks",
        "wireName": "weeks[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by week numbers"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB team game statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/player_season_stats",
    "name": "ncaab_get_player_season_stats",
    "title": "Get NCAAB player season statistics",
    "description": "Get NCAAB player season statistics\n\nGet player season averages. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/player_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB player season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/team_season_stats",
    "name": "ncaab_get_team_season_stats",
    "title": "Get NCAAB team season statistics",
    "description": "Get NCAAB team season statistics\n\nGet team season averages. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaab/v1/team_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB team season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/bracket",
    "name": "ncaab_get_brackets",
    "title": "Get NCAAB tournament bracket data",
    "description": "Get NCAAB tournament bracket data\n\nRetrieve NCAA Men's Basketball tournament bracket data with optional filters (GOAT tier).\nSeason values are offset by -1 from database values.\n\nRound IDs:\n- 1: First Four/Play-in games\n- 2: Round of 64 (First Round)\n- 3: Round of 32 (Second Round)\n- 4: Sweet 16 (Regional Semifinals)\n- 5: Elite 8 (Regional Finals)\n- 6: Final Four (National Semifinals)\n- 7: Championship (National Championship)",
    "method": "GET",
    "path": "/ncaab/v1/bracket",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 queries database for 2026)"
        },
        "round_id": {
          "type": "integer",
          "minimum": 1,
          "maximum": 7,
          "description": "Filter by tournament round (1-7)"
        },
        "region_id": {
          "type": "integer",
          "description": "Filter by region ID"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 queries database for 2026)"
        }
      },
      {
        "publicName": "round_id",
        "wireName": "round_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "minimum": 1,
          "maximum": 7,
          "description": "Filter by tournament round (1-7)"
        }
      },
      {
        "publicName": "region_id",
        "wireName": "region_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by region ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB tournament bracket data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/odds",
    "name": "ncaab_get_betting_odds",
    "title": "Get NCAAB betting odds",
    "description": "Get NCAAB betting odds\n\nRetrieve betting odds for NCAAB games. Either dates or game_ids is required.",
    "method": "GET",
    "path": "/ncaab/v1/odds",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates (YYYY-MM-DD format)"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates (YYYY-MM-DD format)"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaab.yml",
    "operationKey": "GET /ncaab/v1/odds/opening",
    "name": "ncaab_get_odds_opening",
    "title": "Get NCAAB opening betting odds",
    "description": "Get NCAAB opening betting odds\n\nRetrieve historical opening betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/ncaab/v1/odds/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAB opening betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
