// Generated by scripts/generate-openapi-tools.mjs from openapi/ncaaw.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const ncaawOperations = [
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/conferences",
    "name": "ncaaw_get_conferences",
    "title": "Get NCAAW conferences",
    "description": "Get NCAAW conferences",
    "method": "GET",
    "path": "/ncaaw/v1/conferences",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW conferences",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/conferences/{id}",
    "name": "ncaaw_get_conference_by_id",
    "title": "Get specific NCAAW conference",
    "description": "Get specific NCAAW conference",
    "method": "GET",
    "path": "/ncaaw/v1/conferences/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Conference ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Conference ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAW conference",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/teams",
    "name": "ncaaw_get_teams",
    "title": "Get NCAAW teams",
    "description": "Get NCAAW teams",
    "method": "GET",
    "path": "/ncaaw/v1/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conference_id": {
          "type": "integer",
          "description": "Filter by conference ID"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "conference_id",
        "wireName": "conference_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by conference ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW teams",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/teams/{id}",
    "name": "ncaaw_get_team_by_id",
    "title": "Get specific NCAAW team",
    "description": "Get specific NCAAW team",
    "method": "GET",
    "path": "/ncaaw/v1/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Team ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Team ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAW team",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/players",
    "name": "ncaaw_get_players",
    "title": "Get NCAAW players",
    "description": "Get NCAAW players",
    "method": "GET",
    "path": "/ncaaw/v1/players",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/players/{id}",
    "name": "ncaaw_get_player_by_id",
    "title": "Get specific NCAAW player",
    "description": "Get specific NCAAW player",
    "method": "GET",
    "path": "/ncaaw/v1/players/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Player ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Player ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAW player",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/players/active",
    "name": "ncaaw_get_active_players",
    "title": "Get active NCAAW players",
    "description": "Get active NCAAW players",
    "method": "GET",
    "path": "/ncaaw/v1/players/active",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get active NCAAW players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/standings",
    "name": "ncaaw_get_standings",
    "title": "Get NCAAW team standings",
    "description": "Get NCAAW team standings\n\nGet team standings. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "season": {
          "type": "integer",
          "description": "Season year (e.g. 2025 for 2025-26 season)"
        },
        "conference_id": {
          "type": "integer",
          "description": "Filter by conference ID (required)"
        }
      },
      "additionalProperties": false,
      "required": [
        "conference_id"
      ]
    },
    "parameters": [
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "conference_id",
        "wireName": "conference_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by conference ID (required)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW team standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/games",
    "name": "ncaaw_get_games",
    "title": "Get NCAAW games",
    "description": "Get NCAAW games\n\nGet games. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/games",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date (YYYY-MM-DD)"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date (YYYY-MM-DD)"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date (YYYY-MM-DD)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW games",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/games/{id}",
    "name": "ncaaw_get_game_by_id",
    "title": "Get specific NCAAW game",
    "description": "Get specific NCAAW game",
    "method": "GET",
    "path": "/ncaaw/v1/games/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Game ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Game ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAW game",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/rankings",
    "name": "ncaaw_get_rankings",
    "title": "Get NCAAW rankings",
    "description": "Get NCAAW rankings\n\nGet team rankings. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/rankings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season). Required."
        },
        "week": {
          "type": "integer",
          "description": "Filter by week number"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season). Required."
        }
      },
      {
        "publicName": "week",
        "wireName": "week",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by week number"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW rankings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/plays",
    "name": "ncaaw_get_plays",
    "title": "Get NCAAW play-by-play data",
    "description": "Get NCAAW play-by-play data",
    "method": "GET",
    "path": "/ncaaw/v1/plays",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "Game ID (required)"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Game ID (required)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW play-by-play data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/player_stats",
    "name": "ncaaw_get_player_stats",
    "title": "Get NCAAW player game statistics",
    "description": "Get NCAAW player game statistics\n\nGet player statistics. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/player_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW player game statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/team_stats",
    "name": "ncaaw_get_team_stats",
    "title": "Get NCAAW team game statistics",
    "description": "Get NCAAW team game statistics\n\nGet team statistics. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/team_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW team game statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/player_season_stats",
    "name": "ncaaw_get_player_season_stats",
    "title": "Get NCAAW player season statistics",
    "description": "Get NCAAW player season statistics\n\nGet player season averages. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/player_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW player season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/team_season_stats",
    "name": "ncaaw_get_team_season_stats",
    "title": "Get NCAAW team season statistics",
    "description": "Get NCAAW team season statistics\n\nGet team season averages. Note - season values are transformed (user sends 2025, API queries DB for 2026, returns 2025)",
    "method": "GET",
    "path": "/ncaaw/v1/team_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 for 2025-26 season)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW team season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/bracket",
    "name": "ncaaw_get_brackets",
    "title": "Get NCAAW tournament bracket data",
    "description": "Get NCAAW tournament bracket data\n\nRetrieve NCAA Women's Basketball tournament bracket data with optional filters (GOAT tier).\nSeason values are offset by -1 from database values.\n\nRound IDs:\n- 0: First Four/Play-in games\n- 1: Round of 64 (First Round)\n- 2: Round of 32 (Second Round)\n- 3: Sweet 16 (Regional Semifinals)\n- 4: Elite 8 (Regional Finals)\n- 5: Final Four (National Semifinals)\n- 6: Championship (National Championship)",
    "method": "GET",
    "path": "/ncaaw/v1/bracket",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 queries database for 2026)"
        },
        "round_id": {
          "type": "integer",
          "minimum": 0,
          "maximum": 6,
          "description": "Filter by tournament round (0-6)"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (e.g. 2025 queries database for 2026)"
        }
      },
      {
        "publicName": "round_id",
        "wireName": "round_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "minimum": 0,
          "maximum": 6,
          "description": "Filter by tournament round (0-6)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW tournament bracket data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/odds",
    "name": "ncaaw_get_betting_odds",
    "title": "Get NCAAW betting odds",
    "description": "Get NCAAW betting odds\n\nRetrieve betting odds for NCAAW games. Either dates or game_ids is required. Note that NCAAW odds data is sparse — coverage is limited compared to other sports, and not all games will have odds available. Data is only available from the 2025-2026 season onwards.",
    "method": "GET",
    "path": "/ncaaw/v1/odds",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates (YYYY-MM-DD format)"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates (YYYY-MM-DD format)"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaw.yml",
    "operationKey": "GET /ncaaw/v1/odds/opening",
    "name": "ncaaw_get_odds_opening",
    "title": "Get NCAAW opening betting odds",
    "description": "Get NCAAW opening betting odds\n\nRetrieve historical opening betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/ncaaw/v1/odds/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAW opening betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
