// Generated by scripts/generate-openapi-tools.mjs from openapi/ncaaf.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const ncaafOperations = [
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/conferences",
    "name": "ncaaf_get_conferences",
    "title": "Get NCAAF conferences",
    "description": "Get NCAAF conferences",
    "method": "GET",
    "path": "/ncaaf/v1/conferences",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "parameters": [],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF conferences",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/conferences/{id}",
    "name": "ncaaf_get_conference_by_id",
    "title": "Get specific NCAAF conference",
    "description": "Get specific NCAAF conference",
    "method": "GET",
    "path": "/ncaaf/v1/conferences/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Conference ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Conference ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAF conference",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/teams",
    "name": "ncaaf_get_teams",
    "title": "Get NCAAF teams",
    "description": "Get NCAAF teams",
    "method": "GET",
    "path": "/ncaaf/v1/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conference_id": {
          "type": "integer",
          "description": "Filter by conference id"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "conference_id",
        "wireName": "conference_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by conference id"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF teams",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/teams/{id}",
    "name": "ncaaf_get_team_by_id",
    "title": "Get specific NCAAF team",
    "description": "Get specific NCAAF team",
    "method": "GET",
    "path": "/ncaaf/v1/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Team ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Team ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAF team",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/players",
    "name": "ncaaf_get_players",
    "title": "Get NCAAF players",
    "description": "Get NCAAF players",
    "method": "GET",
    "path": "/ncaaf/v1/players",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/players/active",
    "name": "ncaaf_get_active_players",
    "title": "Get active NCAAF players",
    "description": "Get active NCAAF players",
    "method": "GET",
    "path": "/ncaaf/v1/players/active",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get active NCAAF players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/players/{id}",
    "name": "ncaaf_get_player_by_id",
    "title": "Get specific NCAAF player",
    "description": "Get specific NCAAF player",
    "method": "GET",
    "path": "/ncaaf/v1/players/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Player ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Player ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAF player",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/standings",
    "name": "ncaaf_get_standings",
    "title": "Get NCAAF standings",
    "description": "Get NCAAF standings",
    "method": "GET",
    "path": "/ncaaf/v1/standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conference_id": {
          "type": "integer",
          "description": "Conference ID (required)"
        },
        "season": {
          "type": "integer",
          "description": "Season year (required)"
        }
      },
      "additionalProperties": false,
      "required": [
        "conference_id",
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "conference_id",
        "wireName": "conference_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Conference ID (required)"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year (required)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/games",
    "name": "ncaaf_get_games",
    "title": "Get NCAAF games",
    "description": "Get NCAAF games",
    "method": "GET",
    "path": "/ncaaf/v1/games",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date"
        },
        "weeks": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by weeks"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date"
        }
      },
      {
        "publicName": "weeks",
        "wireName": "weeks[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by weeks"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF games",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/games/{id}",
    "name": "ncaaf_get_game_by_id",
    "title": "Get specific NCAAF game",
    "description": "Get specific NCAAF game",
    "method": "GET",
    "path": "/ncaaf/v1/games/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Game ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Game ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific NCAAF game",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/rankings",
    "name": "ncaaf_get_rankings",
    "title": "Get NCAAF rankings",
    "description": "Get NCAAF rankings",
    "method": "GET",
    "path": "/ncaaf/v1/rankings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "season": {
          "type": "integer",
          "description": "Season year (required)"
        },
        "week": {
          "type": "integer",
          "description": "Filter by week"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year (required)"
        }
      },
      {
        "publicName": "week",
        "wireName": "week",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by week"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF rankings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/plays",
    "name": "ncaaf_get_plays",
    "title": "Get NCAAF play-by-play data",
    "description": "Get NCAAF play-by-play data",
    "method": "GET",
    "path": "/ncaaf/v1/plays",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "Game ID (required)"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Game ID (required)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF play-by-play data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/player_stats",
    "name": "ncaaf_get_player_stats",
    "title": "Get NCAAF player statistics",
    "description": "Get NCAAF player statistics",
    "method": "GET",
    "path": "/ncaaf/v1/player_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        },
        "weeks": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by weeks"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      {
        "publicName": "weeks",
        "wireName": "weeks[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by weeks"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF player statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/team_stats",
    "name": "ncaaf_get_team_stats",
    "title": "Get NCAAF team statistics",
    "description": "Get NCAAF team statistics",
    "method": "GET",
    "path": "/ncaaf/v1/team_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        },
        "weeks": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by weeks"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      {
        "publicName": "weeks",
        "wireName": "weeks[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by weeks"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF team statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/player_season_stats",
    "name": "ncaaf_get_player_season_stats",
    "title": "Get NCAAF player season statistics",
    "description": "Get NCAAF player season statistics",
    "method": "GET",
    "path": "/ncaaf/v1/player_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF player season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/team_season_stats",
    "name": "ncaaf_get_team_season_stats",
    "title": "Get NCAAF team season statistics",
    "description": "Get NCAAF team season statistics",
    "method": "GET",
    "path": "/ncaaf/v1/team_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF team season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/odds",
    "name": "ncaaf_get_betting_odds",
    "title": "Get NCAAF betting odds",
    "description": "Get NCAAF betting odds\n\nRetrieve betting odds for NCAAF games. Either (season and week) or game_ids is required.",
    "method": "GET",
    "path": "/ncaaf/v1/odds",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season (must be provided with week)"
        },
        "week": {
          "type": "integer",
          "description": "Filter by week (must be provided with season)"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season (must be provided with week)"
        }
      },
      {
        "publicName": "week",
        "wireName": "week",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by week (must be provided with season)"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/odds/opening",
    "name": "ncaaf_get_odds_opening",
    "title": "Get NCAAF opening betting odds",
    "description": "Get NCAAF opening betting odds\n\nRetrieve historical opening betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/ncaaf/v1/odds/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        },
        "week": {
          "type": "integer",
          "description": "Filter by week"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      {
        "publicName": "week",
        "wireName": "week",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by week"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF opening betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/ncaaf.yml",
    "operationKey": "GET /ncaaf/v1/odds/player_props/opening",
    "name": "ncaaf_get_odds_player_props_opening",
    "title": "Get NCAAF opening player prop odds",
    "description": "Get NCAAF opening player prop odds\n\nRetrieve historical opening player prop betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/ncaaf/v1/odds/player_props/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID to retrieve opening player props for"
        },
        "player_id": {
          "type": "integer",
          "description": "Filter props for a specific player"
        },
        "prop_type": {
          "type": "string",
          "description": "Filter by prop type"
        },
        "vendors": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID to retrieve opening player props for"
        }
      },
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter props for a specific player"
        }
      },
      {
        "publicName": "prop_type",
        "wireName": "prop_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by prop type"
        }
      },
      {
        "publicName": "vendors",
        "wireName": "vendors",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get NCAAF opening player prop odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
