// Generated by scripts/generate-openapi-tools.mjs from openapi/wnba.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { GeneratedOperationDefinition } from "../types.js";

export const wnbaOperations = [
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/teams",
    "name": "wnba_get_teams",
    "title": "Get WNBA teams",
    "description": "Get WNBA teams",
    "method": "GET",
    "path": "/wnba/v1/teams",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conference": {
          "type": "string",
          "enum": [
            "Eastern",
            "Western"
          ],
          "description": "Filter by conference"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "conference",
        "wireName": "conference",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "Eastern",
            "Western"
          ],
          "description": "Filter by conference"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA teams",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/teams/{id}",
    "name": "wnba_get_team_by_id",
    "title": "Get specific WNBA team",
    "description": "Get specific WNBA team",
    "method": "GET",
    "path": "/wnba/v1/teams/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Team ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Team ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific WNBA team",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/players",
    "name": "wnba_get_players",
    "title": "Get WNBA players",
    "description": "Get WNBA players",
    "method": "GET",
    "path": "/wnba/v1/players",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/players/active",
    "name": "wnba_get_active_players",
    "title": "Get active WNBA players",
    "description": "Get active WNBA players",
    "method": "GET",
    "path": "/wnba/v1/players/active",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "search": {
          "type": "string",
          "description": "Search by player name"
        },
        "first_name": {
          "type": "string",
          "description": "Filter by first name"
        },
        "last_name": {
          "type": "string",
          "description": "Filter by last name"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "search",
        "wireName": "search",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Search by player name"
        }
      },
      {
        "publicName": "first_name",
        "wireName": "first_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by first name"
        }
      },
      {
        "publicName": "last_name",
        "wireName": "last_name",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by last name"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get active WNBA players",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/players/{id}",
    "name": "wnba_get_player_by_id",
    "title": "Get specific WNBA player",
    "description": "Get specific WNBA player",
    "method": "GET",
    "path": "/wnba/v1/players/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Player ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Player ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific WNBA player",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/games",
    "name": "wnba_get_games",
    "title": "Get WNBA games",
    "description": "Get WNBA games",
    "method": "GET",
    "path": "/wnba/v1/games",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date"
        },
        "season_type": {
          "type": "string",
          "description": "Filter by season type"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter games before this date"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by season type"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA games",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/games/{id}",
    "name": "wnba_get_game_by_id",
    "title": "Get specific WNBA game",
    "description": "Get specific WNBA game",
    "method": "GET",
    "path": "/wnba/v1/games/{id}",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Game ID"
        }
      },
      "additionalProperties": false,
      "required": [
        "id"
      ]
    },
    "parameters": [
      {
        "publicName": "id",
        "wireName": "id",
        "location": "path",
        "required": true,
        "style": "simple",
        "explode": false,
        "schema": {
          "type": "integer",
          "description": "Game ID"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get specific WNBA game",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/player_stats",
    "name": "wnba_get_player_stats",
    "title": "Get WNBA player statistics",
    "description": "Get WNBA player statistics",
    "method": "GET",
    "path": "/wnba/v1/player_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/team_stats",
    "name": "wnba_get_team_stats",
    "title": "Get WNBA team statistics",
    "description": "Get WNBA team statistics",
    "method": "GET",
    "path": "/wnba/v1/team_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter stats before this date"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA team statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/player_season_stats",
    "name": "wnba_get_player_season_stats",
    "title": "Get WNBA player season statistics",
    "description": "Get WNBA player season statistics",
    "method": "GET",
    "path": "/wnba/v1/player_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        },
        "season_type": {
          "type": "integer",
          "description": "Filter by season type"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season type"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/team_season_stats",
    "name": "wnba_get_team_season_stats",
    "title": "Get WNBA team season statistics",
    "description": "Get WNBA team season statistics",
    "method": "GET",
    "path": "/wnba/v1/team_season_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        },
        "season_type": {
          "type": "integer",
          "description": "Filter by season type"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season type"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA team season statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/player_game_advanced_stats",
    "name": "wnba_get_player_game_advanced_stats",
    "title": "Get WNBA player game advanced statistics",
    "description": "Get WNBA player game advanced statistics",
    "method": "GET",
    "path": "/wnba/v1/player_game_advanced_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason status"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or before this date"
        },
        "period": {
          "type": "integer",
          "description": "Filter by period; 0 represents full game"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason status"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or before this date"
        }
      },
      {
        "publicName": "period",
        "wireName": "period",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by period; 0 represents full game"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player game advanced statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/team_game_advanced_stats",
    "name": "wnba_get_team_game_advanced_stats",
    "title": "Get WNBA team game advanced statistics",
    "description": "Get WNBA team game advanced statistics",
    "method": "GET",
    "path": "/wnba/v1/team_game_advanced_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        },
        "season": {
          "type": "integer",
          "description": "Filter by season"
        },
        "seasons": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason status"
        },
        "start_date": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or after this date"
        },
        "end_date": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or before this date"
        },
        "period": {
          "type": "integer",
          "description": "Filter by period; 0 represents full game"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by dates (YYYY-MM-DD)"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      {
        "publicName": "seasons",
        "wireName": "seasons[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by seasons"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason status"
        }
      },
      {
        "publicName": "start_date",
        "wireName": "start_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or after this date"
        }
      },
      {
        "publicName": "end_date",
        "wireName": "end_date",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "format": "date",
          "description": "Filter by games on or before this date"
        }
      },
      {
        "publicName": "period",
        "wireName": "period",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by period; 0 represents full game"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA team game advanced statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/player_season_advanced_stats",
    "name": "wnba_get_player_season_advanced_stats",
    "title": "Get WNBA player season advanced statistics",
    "description": "Get WNBA player season advanced statistics",
    "method": "GET",
    "path": "/wnba/v1/player_season_advanced_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Season year"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason status"
        },
        "scope": {
          "type": "string",
          "default": "general",
          "enum": [
            "general",
            "clutch"
          ],
          "description": "Filter by stat scope"
        },
        "measure_type": {
          "type": "string",
          "enum": [
            "advanced",
            "misc",
            "scoring",
            "usage",
            "defense",
            "four_factors",
            "opponent",
            "base"
          ],
          "description": "Filter by stat category"
        },
        "per_mode": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason status"
        }
      },
      {
        "publicName": "scope",
        "wireName": "scope",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "general",
          "enum": [
            "general",
            "clutch"
          ],
          "description": "Filter by stat scope"
        }
      },
      {
        "publicName": "measure_type",
        "wireName": "measure_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "advanced",
            "misc",
            "scoring",
            "usage",
            "defense",
            "four_factors",
            "opponent",
            "base"
          ],
          "description": "Filter by stat category"
        }
      },
      {
        "publicName": "per_mode",
        "wireName": "per_mode",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player season advanced statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/team_season_advanced_stats",
    "name": "wnba_get_team_season_advanced_stats",
    "title": "Get WNBA team season advanced statistics",
    "description": "Get WNBA team season advanced statistics",
    "method": "GET",
    "path": "/wnba/v1/team_season_advanced_stats",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Season year"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason status"
        },
        "scope": {
          "type": "string",
          "default": "general",
          "enum": [
            "general",
            "clutch"
          ],
          "description": "Filter by stat scope"
        },
        "measure_type": {
          "type": "string",
          "enum": [
            "advanced",
            "misc",
            "scoring",
            "usage",
            "defense",
            "four_factors",
            "opponent",
            "base"
          ],
          "description": "Filter by stat category"
        },
        "per_mode": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason status"
        }
      },
      {
        "publicName": "scope",
        "wireName": "scope",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "general",
          "enum": [
            "general",
            "clutch"
          ],
          "description": "Filter by stat scope"
        }
      },
      {
        "publicName": "measure_type",
        "wireName": "measure_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "advanced",
            "misc",
            "scoring",
            "usage",
            "defense",
            "four_factors",
            "opponent",
            "base"
          ],
          "description": "Filter by stat category"
        }
      },
      {
        "publicName": "per_mode",
        "wireName": "per_mode",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA team season advanced statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/player_shot_locations",
    "name": "wnba_get_player_shot_locations",
    "title": "Get WNBA player shot location statistics",
    "description": "Get WNBA player shot location statistics",
    "method": "GET",
    "path": "/wnba/v1/player_shot_locations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Season year"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason status"
        },
        "distance_range": {
          "type": "string",
          "default": "by_zone",
          "enum": [
            "by_zone",
            "5ft_range"
          ],
          "description": "Filter shot locations by distance grouping"
        },
        "per_mode": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason status"
        }
      },
      {
        "publicName": "distance_range",
        "wireName": "distance_range",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "by_zone",
          "enum": [
            "by_zone",
            "5ft_range"
          ],
          "description": "Filter shot locations by distance grouping"
        }
      },
      {
        "publicName": "per_mode",
        "wireName": "per_mode",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player shot location statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/team_shot_locations",
    "name": "wnba_get_team_shot_locations",
    "title": "Get WNBA team shot location statistics",
    "description": "Get WNBA team shot location statistics",
    "method": "GET",
    "path": "/wnba/v1/team_shot_locations",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "season": {
          "type": "integer",
          "description": "Season year"
        },
        "season_type": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        },
        "postseason": {
          "type": "boolean",
          "description": "Filter by postseason status"
        },
        "measure_type": {
          "type": "string",
          "enum": [
            "advanced",
            "misc",
            "scoring",
            "usage",
            "defense",
            "four_factors",
            "opponent",
            "base"
          ],
          "description": "Filter by stat category"
        },
        "distance_range": {
          "type": "string",
          "default": "by_zone",
          "enum": [
            "by_zone",
            "5ft_range"
          ],
          "description": "Filter shot locations by distance grouping"
        },
        "per_mode": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      },
      "additionalProperties": false,
      "required": [
        "season"
      ]
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Season year"
        }
      },
      {
        "publicName": "season_type",
        "wireName": "season_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "regular",
            "playoffs"
          ],
          "description": "Filter by season type"
        }
      },
      {
        "publicName": "postseason",
        "wireName": "postseason",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "boolean",
          "description": "Filter by postseason status"
        }
      },
      {
        "publicName": "measure_type",
        "wireName": "measure_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "advanced",
            "misc",
            "scoring",
            "usage",
            "defense",
            "four_factors",
            "opponent",
            "base"
          ],
          "description": "Filter by stat category"
        }
      },
      {
        "publicName": "distance_range",
        "wireName": "distance_range",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "by_zone",
          "enum": [
            "by_zone",
            "5ft_range"
          ],
          "description": "Filter shot locations by distance grouping"
        }
      },
      {
        "publicName": "per_mode",
        "wireName": "per_mode",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "default": "totals",
          "enum": [
            "totals",
            "per_game"
          ],
          "description": "Filter by stat aggregation mode"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA team shot location statistics",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/standings",
    "name": "wnba_get_standings",
    "title": "Get WNBA standings",
    "description": "Get WNBA standings",
    "method": "GET",
    "path": "/wnba/v1/standings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "season": {
          "type": "integer",
          "description": "Filter by season"
        },
        "conference": {
          "type": "string",
          "enum": [
            "Eastern",
            "Western"
          ],
          "description": "Filter by conference"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "season",
        "wireName": "season",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter by season"
        }
      },
      {
        "publicName": "conference",
        "wireName": "conference",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "enum": [
            "Eastern",
            "Western"
          ],
          "description": "Filter by conference"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA standings",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/player_injuries",
    "name": "wnba_get_player_injuries",
    "title": "Get WNBA player injuries",
    "description": "Get WNBA player injuries",
    "method": "GET",
    "path": "/wnba/v1/player_injuries",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "team_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        },
        "player_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "team_ids",
        "wireName": "team_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by team IDs"
        }
      },
      {
        "publicName": "player_ids",
        "wireName": "player_ids[]",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by player IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player injuries",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/odds",
    "name": "wnba_get_odds",
    "title": "Get WNBA betting odds",
    "description": "Get WNBA betting odds\n\nRetrieve betting odds for WNBA games. Either dates or game_ids is required.",
    "method": "GET",
    "path": "/wnba/v1/odds",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by specific dates (YYYY-MM-DD format)"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by specific dates (YYYY-MM-DD format)"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/odds/opening",
    "name": "wnba_get_odds_opening",
    "title": "Get WNBA opening betting odds",
    "description": "Get WNBA opening betting odds\n\nRetrieve historical opening betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/wnba/v1/odds/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "cursor": {
          "type": "integer",
          "description": "The cursor for pagination"
        },
        "per_page": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        },
        "game_ids": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        },
        "dates": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      },
      "additionalProperties": false
    },
    "parameters": [
      {
        "publicName": "cursor",
        "wireName": "cursor",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The cursor for pagination"
        }
      },
      {
        "publicName": "per_page",
        "wireName": "per_page",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "maximum": 100,
          "default": 25,
          "description": "Number of results per page"
        }
      },
      {
        "publicName": "game_ids",
        "wireName": "game_ids",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Filter by game IDs"
        }
      },
      {
        "publicName": "dates",
        "wireName": "dates",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "date"
          },
          "description": "Filter by game dates"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA opening betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/odds/player_props",
    "name": "wnba_get_odds_player_props",
    "title": "Get WNBA player prop betting odds",
    "description": "Get WNBA player prop betting odds\n\nRetrieve live player prop betting data for WNBA games. Player prop data is LIVE and updated in real-time.\nWe do not store historical data. As games near completion, many (or all) player props may be removed from sportsbooks.\n\n**Note:** This endpoint returns all player props for the specified game in a single response. Pagination is not supported.\n\nThe API supports two market types:\n- **over_under**: Traditional over/under markets where users can bet on whether a player will go over or under a specific line value\n- **milestone**: Milestone markets where users bet on whether a player will reach a specific achievement",
    "method": "GET",
    "path": "/wnba/v1/odds/player_props",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID to retrieve player props for (required)"
        },
        "player_id": {
          "type": "integer",
          "description": "Filter props for a specific player"
        },
        "prop_type": {
          "type": "string",
          "description": "Filter by prop type"
        },
        "vendors": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by specific sportsbook vendors. If not provided, returns props from all available vendors."
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID to retrieve player props for (required)"
        }
      },
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter props for a specific player"
        }
      },
      {
        "publicName": "prop_type",
        "wireName": "prop_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by prop type"
        }
      },
      {
        "publicName": "vendors",
        "wireName": "vendors",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by specific sportsbook vendors. If not provided, returns props from all available vendors."
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA player prop betting odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/odds/player_props/opening",
    "name": "wnba_get_odds_player_props_opening",
    "title": "Get WNBA opening player prop odds",
    "description": "Get WNBA opening player prop odds\n\nRetrieve historical opening player prop betting odds. Coverage is limited to the most recently completed season and ongoing seasons where available. Requires GOAT tier.",
    "method": "GET",
    "path": "/wnba/v1/odds/player_props/opening",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "The game ID to retrieve opening player props for"
        },
        "player_id": {
          "type": "integer",
          "description": "Filter props for a specific player"
        },
        "prop_type": {
          "type": "string",
          "description": "Filter by prop type"
        },
        "vendors": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "The game ID to retrieve opening player props for"
        }
      },
      {
        "publicName": "player_id",
        "wireName": "player_id",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Filter props for a specific player"
        }
      },
      {
        "publicName": "prop_type",
        "wireName": "prop_type",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "string",
          "description": "Filter by prop type"
        }
      },
      {
        "publicName": "vendors",
        "wireName": "vendors",
        "location": "query",
        "required": false,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Filter by sportsbook vendors"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA opening player prop odds",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  },
  {
    "sourceFile": "openapi/wnba.yml",
    "operationKey": "GET /wnba/v1/plays",
    "name": "wnba_get_plays",
    "title": "Get WNBA play-by-play data",
    "description": "Get WNBA play-by-play data",
    "method": "GET",
    "path": "/wnba/v1/plays",
    "inputSchema": {
      "type": "object",
      "properties": {
        "game_id": {
          "type": "integer",
          "description": "Game ID (required)"
        }
      },
      "additionalProperties": false,
      "required": [
        "game_id"
      ]
    },
    "parameters": [
      {
        "publicName": "game_id",
        "wireName": "game_id",
        "location": "query",
        "required": true,
        "style": "form",
        "explode": true,
        "schema": {
          "type": "integer",
          "description": "Game ID (required)"
        }
      }
    ],
    "security": "apiKey",
    "sensitive": false,
    "redactResponseFields": [],
    "sensitiveResponseUrlFields": [],
    "annotations": {
      "title": "Get WNBA play-by-play data",
      "readOnlyHint": true,
      "destructiveHint": false,
      "idempotentHint": true,
      "openWorldHint": true
    }
  }
] satisfies GeneratedOperationDefinition[];
