// Generated by scripts/generate-openapi-tools.mjs from openapi/bundesliga.yml
// BALLDONTLIE API source commit: 3b8fdeee2d31f6aa9fca54a9386d478d8862f513
// DO NOT EDIT BY HAND.

import type { APIClient } from "../client.js";
import type { MCPTool, ToolFactoryOptions } from "../types.js";
import { createToolsFromDefinitions } from "../tool-factory.js";
import { soccerOperations } from "../schemas/soccer-schemas.js";

export function createBundesligaTools(apiClient: APIClient, options: ToolFactoryOptions = {}): MCPTool[] {
  return createToolsFromDefinitions(soccerOperations.bundesliga, apiClient, options);
}
