// Generated by scripts/generate-openapi-tools.mjs from openapi/dota.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { APIClient } from "../client.js";
import type { MCPTool, ToolFactoryOptions } from "../types.js";
import { createToolsFromDefinitions } from "../tool-factory.js";
import { dotaOperations } from "../schemas/dota-schemas.js";

export function createDotaTools(apiClient: APIClient, options: ToolFactoryOptions = {}): MCPTool[] {
  return createToolsFromDefinitions(dotaOperations, apiClient, options);
}
