// Generated by scripts/generate-openapi-tools.mjs from openapi/nba.yml
// BALLDONTLIE API source commit: 3b8fdeee2d31f6aa9fca54a9386d478d8862f513
// DO NOT EDIT BY HAND.

import type { APIClient } from "../client.js";
import type { MCPTool, ToolFactoryOptions } from "../types.js";
import { createToolsFromDefinitions } from "../tool-factory.js";
import { nbaOperations } from "../schemas/nba-schemas.js";

export function createNBATools(apiClient: APIClient, options: ToolFactoryOptions = {}): MCPTool[] {
  return createToolsFromDefinitions(nbaOperations, apiClient, options);
}
