// Generated by scripts/generate-openapi-tools.mjs from openapi/ncaaw.yml
// BALLDONTLIE API source commit: 11ad197b9ab6141bb4c42f6cc19ac78c3cdd0c72
// DO NOT EDIT BY HAND.

import type { APIClient } from "../client.js";
import type { MCPTool, ToolFactoryOptions } from "../types.js";
import { createToolsFromDefinitions } from "../tool-factory.js";
import { ncaawOperations } from "../schemas/ncaaw-schemas.js";

export function createNCAAWTools(apiClient: APIClient, options: ToolFactoryOptions = {}): MCPTool[] {
  return createToolsFromDefinitions(ncaawOperations, apiClient, options);
}
