// Generated by scripts/generate-openapi-tools.mjs from openapi/wta.yml
// BALLDONTLIE API source commit: 3b8fdeee2d31f6aa9fca54a9386d478d8862f513
// DO NOT EDIT BY HAND.

import type { APIClient } from "../client.js";
import type { MCPTool, ToolFactoryOptions } from "../types.js";
import { createToolsFromDefinitions } from "../tool-factory.js";
import { wtaOperations } from "../schemas/wta-schemas.js";

export function createWTATools(apiClient: APIClient, options: ToolFactoryOptions = {}): MCPTool[] {
  return createToolsFromDefinitions(wtaOperations, apiClient, options);
}
